### ISSUE TITLE
Residuals for competing risks models

### ISSUE THREAD

**Issue by graemeleehickey** [drizopoulos/JM#1]
I am getting an error message when attempting to extract event model residuals for competing risks joint models (JM version 1.4-5). A reproducible example is below. 

Fit the competing risks model from the `jointModel` help documentation

```r
library(JM)
data("pbc2.id")
data("pbc2")

# Fit model from jointModel help documentation
pbc2.idCR <- crLong(pbc2.id, "status", "alive")
lmeFit.pbc <- lme(log(serBilir) ~ drug * year, 
                  random = ~ year | id,
                  data = pbc2)
coxCRFit.pbc <- coxph(Surv(years, status2) ~ (drug + sex)*strata + strata(strata), 
                      data = pbc2.idCR,
                      x = TRUE)
jmCRFit.pbc <- jointModel(lmeFit.pbc, coxCRFit.pbc, timeVar = "year", 
                          method = "spline-PH-aGH", 
                          interFact = list(value = ~ strata, data = pbc2.idCR), 
                          CompRisk = TRUE)
```

Then, if I run

```r
residuals(jmCRFit.pbc, process = "Event")
```

the following error message is received: `Error in rep(object$y$d, ni) : invalid 'times' argument`.

Interestingly, if I run

```r
residuals(jmCRFit.pbc, type = "Martingale")
```

i.e. without any `process` argument, I get output. However, I am not sure what the output is.

If these residuals are not supposed to be accessed using competing risks models, perhaps adding a `if (compRisk) stop() else ...` line into the code would be helpful, along the same lines as was done for when a user tries to use `MI = TRUE` with such models.

**Comment by drizopoulos** [comment]
You're correct, the residuals function does not currently work in competing risks settings. I''all add a fix to alert the user about that.
