### ISSUE TITLE
diagnostic plots

### ISSUE THREAD

**Issue by BethPhipps** [drizopoulos/JM#11]
Hi, It looks like with the update that the random intercept diagnostic plots work but the random intercept and slope no longer works.

fitLME <- lme(sqrt(CD4) ~ obstime + obstime:drug, random = ~ obstime | patient, data = aids)
fitSURV <- coxph(Surv(Time, death) ~ drug, data = aids.id, x = TRUE)
fit.JM <- jointModel(fitLME, fitSURV, timeVar = "obstime", method = "piecewise-PH-aGH")

plot(fit.JM, which = 1)
plot(fit.JM, which = 2)
plot(fit.JM, which = 3)
plot(fit.JM, which = 4)

For the final two plots here I get the error 
Error in Zs * b[id.GK, , drop = FALSE] : non-conformable arrays
Thank you for your time!

**Comment by drizopoulos** [comment]
Thanks! I committed a fix for version 1.4-99.

**Comment by IlariaPiergentili** [comment]
Hi, now I have the same problem, what could I do to solve it?
Thanks
