### ISSUE TITLE
Error in aeqSurv(Y)

### ISSUE THREAD

**Issue by statwonk** [drizopoulos/JM#14]
I don't currently have a reproducible example in hand, though I'll work on one.

I'm running into this error message having called `jointModel`,

```r
Error in aeqSurv(Y) : 
  aeqSurv exception, an interval has effective length 0
```

I tracked the `aeqSurv` call down [to `coxph` here](https://github.com/drizopoulos/JM/blob/05bfde1addba3138258cc25bbbb661b4032e6b24/R/initial.surv.R#L87). I noticed really large values in the `Time` variable passed to `initial.surv`. I tracked these down to [this spot](https://github.com/drizopoulos/JM/blob/05bfde1addba3138258cc25bbbb661b4032e6b24/R/jointModel.R#L83).

I'm wondering about the reason for the `exp` here?

```r
Time <- exp(survObject$y[, 1])
```

**Comment by drizopoulos** [comment]
Could you try changing the time scale to, e.g., years. Do you provide a `coxph` or `survreg` object in `joinModel()`?

**Comment by rberch** [comment]
@drizopoulos , @statwonk
Please, I have the same error. Did you find a way to fix this?
