### ISSUE TITLE
problem with scaling of time variables

### ISSUE THREAD

**Issue by CaryOberije** [drizopoulos/JM#16]
Dear Dimitris,
I'm trying to use the JM library, but I get error messages and they seem connected to the time duration units: days or months.

I was using months as time scale and I then got the message: 
"Error in aeqSurv(Y) : 
  aeqSurv exception, an interval has effective length 0"
It seems that this happens if I use months for survival analysis. 

If I change my time variables into duration in days, I get another error message:
"Error in if (t1 || t2) { : missing value where TRUE/FALSE needed"
I found a similar issue here in the GitHub and the advice was not to use days as unit for duration.

I'm a bit stuck with this as nor the days neither the months seem to work. I would very much appreciate it if you could give me some advice?

**Comment by drizopoulos** [comment]
It's difficult to see what is going on without a reproducible example.
