### ISSUE TITLE
Query on using `survfitJM`

### ISSUE THREAD

**Issue by DocEd** [drizopoulos/JM#17]
Hi Prof Rizopoulos,

Is there an implementation that would allow an entirely new subject (outside the model training data) to be used to create dynamic predictions? If for example we have their baseline covariates and longitudinal biomarker data are known.

Thank you in advance.

**Comment by drizopoulos** [comment]
Yes, this is possible by providing the data of this new patient in the newdata argument.

**Comment by DocEd** [comment]
Thank you for the extremely rapid response! I thought that the request for a subject id in the "idVar" argument meant that needed a patient from the training data for an estimate of the random effects. Thank you for clarifying :)
