### ISSUE TITLE
“aeqSurv exception, an interval has effective length 0”

### ISSUE THREAD

**Issue by agstone90** [drizopoulos/JM#19]
Hi Dr. Rizopoulos,

Like a few of the commentors below, I am having an issue with getting my joint model to run, receiving an error
"Error in aeqSurv(Y) : 
  aeqSurv exception, an interval has effective length 0"

My survival object uses the survreg function with weeks as my unit of time. 

`lmefit<-lme(marker~ns(week,3),random=~week|ID,
               data=Data,control=lmeControl(opt="optim"))
survfit<-survreg(Surv(time,status)~covariate,data=Data.id,x=TRUE)
fitjoint<-jointModel(lmefit,survfit,timeVar="week")`

I haven't been able to get any of the fixes  listed [here](https://stackoverflow.com/questions/46988426/error-in-aeqsurvy-aeqsurv-exception-an-interval-has-effective-length-0) to work. The issue doesn't seem to be one of 2 weeks vs 2.0 weeks. Entering "timefix=FALSE" into the survreg call gets an error for an unused argument, and adding 
`aeqSurv(survfit, tolerance = sqrt(.Machine$double.eps))`
returns an error that survfit isn't a Surv object.

Any advice for how to get my model to run would be very appreciated!

Thanks!

**Comment by drizopoulos** [comment]
Have you tried to use coxph instead of survreg?

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________

**Comment by agstone90** [comment]
Hi Dr Rizopoulos,

Thank you so much for responding! It does seem to be running now that I've switched to coxph. Is there a reason that one should work and not the other? Given a time-independent covariate, would both produce the same model?

**Comment by agstone90** [comment]
Hi Dr Rizopoulos,

Thank you so much for responding! It does seem to be running now that I've switched to coxph. Is there a reason that one should work and not the other? Given a time-independent covariate, would both produce the same model?

**Comment by agstone90** [comment]
Hi Dr Rizopoulos,

Thank you so much for responding! It does seem to be running now that I've switched to coxph. Is there a reason that one should work and not the other? Given a time-independent covariate, would both produce the same model?

**Comment by jinjinzhou** [comment]
Even tried coxph model, I still have this error

**Comment by rberch** [comment]
Hi @jinjinzhou, please, did you find a solution to this? I have run into a similar situation.
Thanks

**Comment by jinjinzhou** [comment]
> Hi @jinjinzhou, please, did you find a solution to this? I have run into a similar situation. Thanks

For my situation, it is related to how I bin my longitudinal markers, i.e., some of them were measured on the same day or even more frequently. I filtered those when Tstart-stop < threshold

**Comment by rberch** [comment]
> > Hi @jinjinzhou, please, did you find a solution to this? I have run into a similar situation. Thanks
> 
> For my situation, it is related to how I bin my longitudinal markers, i.e., some of them were measured on the same day or even more frequently. I filtered those when Tstart-stop < threshold

Thank you @jinjinzhou ,

In my case, I am doing a simulation study. I simulate the longitudinal data and survival data (which has the ID, event status, and follow-up time)  using simsurv.
And then when I fit the linear mixed model and coxph, they run without errors.
However, when I run the jointModel, that is when I get the error: 
Error in aeqSurv(Y) : 
  aeqSurv exception, an interval has effective length 0
  I have searched online for possible solutions but I have not found any.

**Comment by mariellabogoni** [comment]
@rberch Did you find a solution? I have the same problem. Thank you!
