### ISSUE TITLE
Infinite or missing values in Hessian at convergence.

### ISSUE THREAD

**Issue by BenGoudsmit** [drizopoulos/JM#21]
Dear prof. Rizopoulos,

My spline-based JM (see below) runs but gives the warning mentioned in the title, and produces incorrect values, and NaN standard-errors, z-values and p-values.
From forums I read a solution that I do not understand? 
https://stackoverflow.com/questions/53130611/error-in-nonlinear-optimization-problem-infinite-or-missing-values-in-x

> surv_splines <- coxph(Surv(years, binstatus) ~ cluster(id) + disease+ age + gender + country, data = survtrain, x = TRUE, model=TRUE)

> spline_lme <- lme(score~ ns(years, df=3) * (disease+ age + gender + country), na.action = na.exclude, random= list(id = pdDiag(form= ~ns(years, df=3))), data=longtrain

> JMsplines <- jointModel(lme_splines_df3,spline_lme, timeVar = "years", method = "spline-PH-aGH")

**Comment by drizopoulos** [comment]
This often indicates a model that is too complicated for the data you have.
