### ISSUE TITLE
survfitJM error: Error in rowMeans(rr, na.rm = TRUE) : 'x' must be numeric

### ISSUE THREAD

**Issue by BenGoudsmit** [drizopoulos/JM#24]
Dear prof. Rizopoulos,

I want to calculate survival probabilities in a 100-patient sample.
All JM functions work lovely, except surfitJM, which throws the abovementioned error.
What does it imply?

```
survfitJM <- JM:::survfitJM.jointModel
sprobs <- survfitJM(JM,testdata,idVar="id",survTimes=c(28/365.25,90/365.25))
```
> Error in rowMeans(rr, na.rm = TRUE) : 'x' must be numeric

**Comment by drizopoulos** [comment]
I cannot reproduce that.

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________

**Comment by BenGoudsmit** [comment]
I understand, to elaborate: if I do not specify survTimes, then sprobs are generated.
However, when specifying certain survTimes it throws the error, which seems strange.

**Comment by BenGoudsmit** [comment]
I discovered that the last.time in the survfitJM function gives an error if the prediction sample is n>1999.
So this works:
```
subsurvtest <- survtest[sample(nrow(survtest), **1999** ), ]
sublongtest <- longtest[longtest$id %in% subsurvtest$id, ]
sub_sprobs <- survfitJM(JM_spline_valslope,sublongtest,idVar="id",
                    last.time=sublongtest$labyrs[sublongtest$counter==1],
                    survTimes=c(2/365.25,7/365.25,28/365.25,90/365.25))
But this does not:
```
```
subsurvtest <- survtest[sample(nrow(survtest), **2000** ), ]
sublongtest <- longtest[longtest$id %in% subsurvtest$id, ]
sub_sprobs <- survfitJM(JM_spline_valslope,sublongtest,idVar="id",
                    last.time=sublongtest$labyrs[sublongtest$counter==1],
                    survTimes=c(2/365.25,7/365.25,28/365.25,90/365.25))
```
With:

> Error in survfitJM: not appropriate value for 'last.time' argument.

Not specifying last.time does work, but again is not what I want.
