### ISSUE TITLE
Trouble with specifying integral form for cumulative effects model

### ISSUE THREAD

**Issue by agstone90** [drizopoulos/JM#26]
Hi Dr. Rizopoulos, thanks again for all the help!

I am trying to fit a cumulative effects model  based on the following lme object

<lme_fit<-lme(var~ns(time,3)+cov,random=~time|ID,
               data=data,control=lmeControl(opt="optim"))>
 
I haven't been able to get the derivForm argument right though. I've been trying

<iform<-list(fixed=~-1+time+ins(time,3)+(cov*time),indFixed=c(1:5),
          random=~-1+time+time^2/2,indRandom=c(1:2))>

and getting an error "Error in terms.formula(derivForm$random) :  invalid model formula in ExtractVars"

Would you be able to provide any guidance as to what the correct syntax would be? 

Thanks!

**Comment by agstone90** [comment]
Sorry, not sure how I've managed to strikethrough my iform.  It should read

>iform<-list(fixed=~-1+time+ins(time,3)+(cov*time),indFixed=c(1:5),
          random=~-1+time+time^2/2,indRandom=c(1:2))

**Comment by drizopoulos** [comment]
You need a tilde to define a formula in R, i.e., fixed = ~...


——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________

**Comment by agstone90** [comment]
Thanks! Managed to delete it when copy/pasting code, but adding an I() operation got it to work.
