### ISSUE TITLE
Confusing point estimates for association parameters in current values + current slopes model

### ISSUE THREAD

**Issue by agstone90** [drizopoulos/JM#27]
Hi Dr. Rizopoulos, 

I am slightly concerned with the point estimates for my association parameters for a current value + current slopes joint model. I am using a large dataset with 91000 observations from 3650 participants. Within a piecewise-PH-GH formulation, estimates for my association parameters for current values plus slope seem funky compared to other parameterizations, and across different baseline hazards (piecewise vs. weibull) they are completely different.

When I used method= "piecewise-PH-GH" in the current values and cumulative effects parameterizations, I got estimates of assoct = 0.2 (SE = 0.01) and assoct.s= 0.01 (SE =0.001) , respectively. When using the current values+ current slopes parameterizations I got estimates of assoct. = -2.05 (SE= 0.25) and assoct.s = 2.25 (SE= 0.25).  Would this sort of difference in hazard ratios be plausible in absence of some sort of issue in numerical integration? 

When I run the current values+ current slopes using method= "weibull-PH-GH", I get point estimates of assoct = 0.36 (SE = 0.24) and assoct.s =  -0.16 (SE=0.24). Is it typical for point estimates to change like this when using different baseline hazard formulations? Is there a way to tell which one is more correct?

Thanks for all the help!

**Comment by drizopoulos** [comment]
Do you use the adaptive Gauss-Hermite?

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________

**Comment by agstone90** [comment]
Yes. When I use the pseudo adaptive Gauss-Hermite, my estimates for the association parameter in the current values only model change direction and reduce by a factor of ten, assoct = -0.02 (SE= 0.01). In the current value+slopes model, pseudo adaptive Gauss-Hermite yields assoct = -1.05 (SE = 0.18) and assoct.s= 1.09 (SE= 0.18).

**Comment by drizopoulos** [comment]
The coefficients' interpretation is different when you only have the value, and when you have the value and slope.

**Comment by agstone90** [comment]
Thank you. Is it normal for point estimates to vary this much between adaptive and pseudo adaptive Gauss Hermite rules?

**Comment by drizopoulos** [comment]
Yes, it can happen depending on the magnitude of the variance of the random effects. The adaptive GH is more trustworthy.

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________
