### ISSUE TITLE
Accept models from lme4 in addition to nlme

### ISSUE THREAD

**Issue by vkehayas** [drizopoulos/JM#3]
Are you considering expanding the capabilities of JM to accept mixed models fitted by the `lme4` package, in addition to those from `nlme`? It seems that `lme4` is still under active development and it's often faster, too, especially with 'crossed' random effects. Thanks for a very useful package, by the way!

**Comment by drizopoulos** [comment]
No, I'm not considering this for package JM. I'm currently put most of my effort in JMbayes (see also GitHub repo) that for multivariate models allows for syntax similar to lme4. Though, for the time being, I don't have immediate plans to include nested and/or crossed random-effects structures.
