### ISSUE TITLE
Error in aeqSurv(Y) :    aeqSurv exception, an interval has effective length 0

### ISSUE THREAD

**Issue by ytripodis** [drizopoulos/JM#30]
I'm running the following in a dataset with 2641 subjects with follow-up in years and time to event between 0.01 and 4.9 years. The lme and the coxfit run with no problems but the jointModel returns 

Error in aeqSurv(Y) :    aeqSurv exception, an interval has effective length 0
 
Time-to-event
Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
0.01369 1.14716 2.00685 2.05442 2.71869 4.86790 

lme.NACC<-lme(Y ~  yrs + AGE + SEX + EDUC,
              random = ~ yrs| NACCID, data=longdata_complete3)

coxfit.NACC<-coxph(Surv(time=timetoevent, event=event) ~  AGE + SEX + EDUC,
               data=survdata_complete2,  x=TRUE)

jointfit.NACC<-jointModel(lme.NACC,coxfit.NACC, timeVar="yrs",
                     method = "piecewise-PH-aGH")

**Comment by drizopoulos** [comment]
I cannot replicate this error.



From: ytripodis ***@***.***>
Sent: Thursday, April 15, 2021 2:03 AM
To: drizopoulos/JM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [drizopoulos/JM] Error in aeqSurv(Y) : aeqSurv exception, an interval has effective length 0 (#30)


I'm running the following in a dataset with 2641 subjects with follow-up in years and time to event between 0.01 and 4.9 years. The lme and the coxfit run with no problems but the jointModel returns

Error in aeqSurv(Y) : aeqSurv exception, an interval has effective length 0

Time-to-event
Min. 1st Qu. Median Mean 3rd Qu. Max.
0.01369 1.14716 2.00685 2.05442 2.71869 4.86790

lme.NACC<-lme(Y ~ yrs + AGE + SEX + EDUC,
random = ~ yrs| NACCID, data=longdata_complete3)

coxfit.NACC<-coxph(Surv(time=timetoevent, event=event) ~ AGE + SEX + EDUC,
data=survdata_complete2, x=TRUE)

jointfit.NACC<-jointModel(lme.NACC,coxfit.NACC, timeVar="yrs",
method = "piecewise-PH-aGH")

-
