### ISSUE TITLE
Error in in optim(thetas, LogLik.splineGH, Score.splineGH, method = "BFGS", 

### ISSUE THREAD

**Issue by AAAAlicebird** [drizopoulos/JM#41]
Hi,
I am a beginner of Joint Models and JM package. While running jointModel() to fit joint models with competing risks, I got the following error:

Error in in optim(thetas, LogLik.splineGH, Score.splineGH, method = "BFGS", optim replies to the infinite value

My code as follow：
fitLME.null <- lme(score_L ~ followyear_L, 
                   random = ~1 | id , data = data2, method = "REML")
coxCRFit.pbc<- coxph(Surv(totalfollow, status2) ~(age +BMI_L+hyp_L+exersice_L)*strata+strata(strata),data = data2.idCR,
                     x = TRUE)

jmCRFit.pbc <- jointModel(fitLME.null, coxCRFit.pbc, timeVar = "followyear_L", 
                          method = "spline-PH-aGH",  
                          interFact = list(value=~strata, data= data2.idCR),
                          CompRisk = T)

score_L is a scale score that ranges from 0 to 30.  Status2 was the event including alive, disease and death. 
All subjects had at least two follow-ups with id as personal identifier.

Any information and advice you could give is much appreciated.

**Comment by drizopoulos** [comment]
This may have to do with the complexity of the model. You could also try the newer JMbayes2 package.
