### ISSUE TITLE
problem running fuction jointModel() in JM package with method = "Cox-PH-aGH" option

### ISSUE THREAD

**Issue by LarbiAluariacy** [drizopoulos/JM#44]
Hi everyone, 
I had this error when running fuction jointModel() in JM package with method = "Cox-PH-aGH" option.

pbc2.id$status2 <- as.numeric(pbc2.id$status != "alive")
pbc2$lserBilir <- log(pbc2$serBilir)

# the linear mixed model
lmeFit1 <- lme(lserBilir ~ year + drug:year, data = pbc2,
                 random = ~ year | id)

# the Cox model
survFit1 <- coxph(Surv(years, status2) ~ drug, data = pbc2.id, x = TRUE)

# the joint model
jointFit1 <- jointModel(lmeFit1, survFit1, timeVar = "year",
                          method = "Cox-PH-aGH")
Error in model.frame.default(data = FALSE, formula = ~long + W1) : 
  'data' must be a data.frame, environment, or list

I cannot fix it since pbc2 and pbc2.id are originally data.frame object.
It runs except with this method option.
Does anyone have any clue?
Thanks!

**Comment by drizopoulos** [comment]
I would advice using the other methods, not the Cox one as it is known to have issues with the estimation of standard errors.
