### ISSUE TITLE
Warning on second run of predict.jointModel

### ISSUE THREAD

**Issue by vkehayas** [drizopoulos/JM#7]
I got a warning after running predict with a `jointModel` for a second time:
> Warning message:
In rm(list = ".Random.seed", envir = globalenv()) :
  object '.Random.seed' not found
 
The reason was that there was no seed to delete with `rm` as it was deleted in the last run and no new seed was created.
I have submitted a pull request (#6) in which I moved the line

`rm(list = ".Random.seed", envir = globalenv())`

inside the `else` clause.

(For a moment I thought it was an error and created the PR, otherwise I may not have bothered you as this does not affect the results.)

**Comment by drizopoulos** [comment]
Thanks for noticing and reporting this.
