### ISSUE TITLE
jointModel() looks for external data.frame

### ISSUE THREAD

**Issue by Currerius** [drizopoulos/JM#8]
... I thought. But it does not. Everything is neat and fine with jointModel().
issue can be closed.

The issue was that lme() stores the *name* of the formula passed to it. *Not* the formula object itself. I think this might be a bug in lme(). 

When passing a list of formulas programmatically to lme() then the reference between the "call" and the "data" objects is broken.

jointModel() references correctly between call and data, but since this does not make any sense, jointModel() throws and error...

**Comment by drizopoulos** [comment]
Thanks for the update!
